[package]
name = "chaft-crypto"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
aes-gcm-siv.workspace = true
chaft-types = { path = "../chaft-types" }
rand_core.workspace = true
serde.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
serde_json.workspace = true
