[package]
name = "chaft-wire"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
chaft-types = { path = "../chaft-types" }
prost.workspace = true
serde_json.workspace = true
thiserror.workspace = true

