[package]
name = "chaft-cli"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
chaft-crypto = { path = "../../security/crypto" }
chaft-identity = { path = "../../security/identity" }
chaft-net = { path = "../../network/transport" }
chaft-net-direct = { path = "../../network/direct" }
chaft-net-iroh = { path = "../../network/iroh" }
chaft-runtime = { path = "../../runtime" }
chaft-types = { path = "../../domain/types" }
clap.workspace = true
serde_json.workspace = true
tokio.workspace = true
