[package]
name = "chaft-cli"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
chaft-crypto = { path = "../../crates/chaft-crypto" }
chaft-identity = { path = "../../crates/chaft-identity" }
chaft-net = { path = "../../crates/chaft-net" }
chaft-net-direct = { path = "../../crates/chaft-net-direct" }
chaft-net-iroh = { path = "../../crates/chaft-net-iroh" }
chaft-runtime = { path = "../../crates/chaft-runtime" }
chaft-types = { path = "../../crates/chaft-types" }
clap.workspace = true
serde_json.workspace = true
tokio.workspace = true
