pragma Singleton
import QtQuick

QtObject {
    readonly property string defaultThemeId: "chaft-signal"
    readonly property string defaultLightThemeId: "chaft-canvas"

    // Every entry must define the full color role set Tokens exposes.
    // catalog[0] is the default theme and the fallback for unknown IDs
    // loaded from desktop.json or CHAFT_THEME. Order here is picker order.
    readonly property var catalog: [
        {
            id: "chaft-signal",
            name: "Chaft Signal",
            tagline: "Brand ink, clear sky, and a quiet coral signal",
            dark: true,
            rail: "#11191d",
            railElevated: "#1b2a33",
            railText: "#f7fafc",
            sidebar: "#151e23",
            sidebarInput: "#202c33",
            sidebarActive: "#263c49",
            sidebarText: "#b8c6cf",
            sidebarTextStrong: "#f7fafc",
            sidebarTextSoft: "#d6e0e6",
            sidebarTextMuted: "#7e919d",
            surfaceBase: "#182024",
            surfaceRaised: "#202a30",
            borderSubtle: "#364750",
            textStrong: "#f6f8fa",
            textMuted: "#a1b0b8",
            accent: "#66beeb",
            onAccent: "#10212a",
            success: "#42bc74",
            secure: "#a4d1f1",
            secureSurface: "#1d3440",
            warning: "#f48058",
            warningSurface: "#3a221d",
            warningText: "#ffb49b"
        },
        {
            id: "chaft-canvas",
            name: "Chaft Canvas",
            tagline: "Soft daylight with confident brand blue",
            dark: false,
            rail: "#e6eef3",
            railElevated: "#ffffff",
            railText: "#182024",
            sidebar: "#eef5f8",
            sidebarInput: "#ffffff",
            sidebarActive: "#d7e9f3",
            sidebarText: "#405561",
            sidebarTextStrong: "#182024",
            sidebarTextSoft: "#2b414d",
            sidebarTextMuted: "#5a707b",
            surfaceBase: "#f7fbfd",
            surfaceRaised: "#ffffff",
            borderSubtle: "#c4d4dd",
            textStrong: "#222426",
            textMuted: "#586d78",
            accent: "#2f54a5",
            onAccent: "#ffffff",
            success: "#248753",
            secure: "#2f54a5",
            secureSurface: "#e3ecf8",
            warning: "#b44928",
            warningSurface: "#fff0eb",
            warningText: "#7b2b16"
        },
        {
            id: "midnight-relay",
            name: "Midnight Relay",
            tagline: "Deep-space indigo with a luminous teal signal",
            dark: true,
            rail: "#0b0d14",
            railElevated: "#1b2030",
            railText: "#f2f5fb",
            sidebar: "#101320",
            sidebarInput: "#1a1e2e",
            sidebarActive: "#232941",
            sidebarText: "#a8b1c7",
            sidebarTextStrong: "#f2f5fb",
            sidebarTextSoft: "#c9d1e4",
            sidebarTextMuted: "#6f7a94",
            surfaceBase: "#12151f",
            surfaceRaised: "#1a1e2b",
            borderSubtle: "#2c3247",
            textStrong: "#e8ecf6",
            textMuted: "#8d97ad",
            accent: "#2dd4bf",
            onAccent: "#071f1c",
            success: "#34d399",
            secure: "#60a5fa",
            secureSurface: "#16233c",
            warning: "#d97706",
            warningSurface: "#33230d",
            warningText: "#fbbf24"
        },
        {
            id: "chaft-classic",
            name: "Chaft Classic",
            tagline: "The original hybrid: dark rails, paper timeline",
            dark: false,
            rail: "#17181f",
            railElevated: "#2a2d3a",
            railText: "#ffffff",
            sidebar: "#20232d",
            sidebarInput: "#2b2f3b",
            sidebarActive: "#313746",
            sidebarText: "#c7ccd8",
            sidebarTextStrong: "#ffffff",
            sidebarTextSoft: "#d8deea",
            sidebarTextMuted: "#8e96a8",
            surfaceBase: "#f7f8fb",
            surfaceRaised: "#ffffff",
            borderSubtle: "#cbd1e2",
            textStrong: "#141824",
            textMuted: "#687285",
            accent: "#0e8385",
            onAccent: "#ffffff",
            success: "#168a5b",
            secure: "#2563a9",
            secureSurface: "#e8f1fc",
            warning: "#9a5b00",
            warningSurface: "#fff6e5",
            warningText: "#684000"
        },
        {
            id: "aurora-borealis",
            name: "Aurora Borealis",
            tagline: "Polar night skies streaked with aurora green",
            dark: true,
            rail: "#061114",
            railElevated: "#10262c",
            railText: "#eafcfc",
            sidebar: "#0a1a1f",
            sidebarInput: "#12262c",
            sidebarActive: "#16333b",
            sidebarText: "#9fc3c9",
            sidebarTextStrong: "#eafcfc",
            sidebarTextSoft: "#c4e3e6",
            sidebarTextMuted: "#5f858c",
            surfaceBase: "#0c1e23",
            surfaceRaised: "#12292f",
            borderSubtle: "#1d3b42",
            textStrong: "#dff7f4",
            textMuted: "#7fa6ab",
            accent: "#4ade80",
            onAccent: "#052613",
            success: "#34d399",
            secure: "#38bdf8",
            secureSurface: "#0c2b3d",
            warning: "#ca8a04",
            warningSurface: "#2d2708",
            warningText: "#fde047"
        },
        {
            id: "synthwave-84",
            name: "Synthwave '84",
            tagline: "Retro grid sunsets in hot pink and violet",
            dark: true,
            rail: "#16091f",
            railElevated: "#2b1440",
            railText: "#fdeeff",
            sidebar: "#1e0d2d",
            sidebarInput: "#2a153e",
            sidebarActive: "#3a1d56",
            sidebarText: "#c3a6dd",
            sidebarTextStrong: "#fdeeff",
            sidebarTextSoft: "#e3c8f2",
            sidebarTextMuted: "#8a6aa6",
            surfaceBase: "#1f1029",
            surfaceRaised: "#2a1738",
            borderSubtle: "#44265f",
            textStrong: "#f8e7ff",
            textMuted: "#a988c4",
            accent: "#ff4fa3",
            onAccent: "#33001a",
            success: "#3ee6a4",
            secure: "#22d3ee",
            secureSurface: "#0e2e3a",
            warning: "#d97706",
            warningSurface: "#362408",
            warningText: "#ffd166"
        },
        {
            id: "neon-district",
            name: "Neon District",
            tagline: "Rain-slicked cyberpunk black, electric yellow",
            dark: true,
            rail: "#0a0a0c",
            railElevated: "#1c1c22",
            railText: "#fafafa",
            sidebar: "#101014",
            sidebarInput: "#1a1a20",
            sidebarActive: "#26262e",
            sidebarText: "#b8b8c4",
            sidebarTextStrong: "#fafafa",
            sidebarTextSoft: "#d8d8e2",
            sidebarTextMuted: "#74747f",
            surfaceBase: "#121218",
            surfaceRaised: "#1b1b22",
            borderSubtle: "#30303a",
            textStrong: "#f2f2f5",
            textMuted: "#8f8f9d",
            accent: "#fde047",
            onAccent: "#1c1900",
            success: "#4ade80",
            secure: "#38bdf8",
            secureSurface: "#10283a",
            warning: "#fb923c",
            warningSurface: "#331c07",
            warningText: "#fdba74"
        },
        {
            id: "deep-current",
            name: "Deep Current",
            tagline: "Abyssal blues lit by bioluminescent cyan",
            dark: true,
            rail: "#04101f",
            railElevated: "#0d2440",
            railText: "#ecf5ff",
            sidebar: "#071a30",
            sidebarInput: "#0e2440",
            sidebarActive: "#133155",
            sidebarText: "#93b4d4",
            sidebarTextStrong: "#ecf5ff",
            sidebarTextSoft: "#bfd8ee",
            sidebarTextMuted: "#587ba0",
            surfaceBase: "#081d33",
            surfaceRaised: "#0e2946",
            borderSubtle: "#1a3a5c",
            textStrong: "#dcecfb",
            textMuted: "#7d9cbd",
            accent: "#22d3ee",
            onAccent: "#03222a",
            success: "#2dd4bf",
            secure: "#818cf8",
            secureSurface: "#1c2247",
            warning: "#d97706",
            warningSurface: "#2f2408",
            warningText: "#fcd34d"
        },
        {
            id: "ember-forge",
            name: "Ember Forge",
            tagline: "Charcoal iron glowing with forge-fire orange",
            dark: true,
            rail: "#140d0a",
            railElevated: "#2b1c15",
            railText: "#fff3ec",
            sidebar: "#1c120d",
            sidebarInput: "#281a13",
            sidebarActive: "#38251b",
            sidebarText: "#d1b3a3",
            sidebarTextStrong: "#fff3ec",
            sidebarTextSoft: "#e8cfc2",
            sidebarTextMuted: "#93705f",
            surfaceBase: "#191009",
            surfaceRaised: "#241811",
            borderSubtle: "#412d1b",
            textStrong: "#f7e8de",
            textMuted: "#b08d78",
            accent: "#f97316",
            onAccent: "#2b1000",
            success: "#4ade80",
            secure: "#e8a33d",
            secureSurface: "#33250e",
            warning: "#dc2626",
            warningSurface: "#370f0f",
            warningText: "#fca5a5"
        },
        {
            id: "terminal-phosphor",
            name: "Terminal Phosphor",
            tagline: "CRT black and green, straight from the mainframe",
            dark: true,
            rail: "#000000",
            railElevated: "#101410",
            railText: "#d8ffd8",
            sidebar: "#060806",
            sidebarInput: "#0e120e",
            sidebarActive: "#142014",
            sidebarText: "#7dbb7d",
            sidebarTextStrong: "#d8ffd8",
            sidebarTextSoft: "#a8dda8",
            sidebarTextMuted: "#4a6b4a",
            surfaceBase: "#030503",
            surfaceRaised: "#0a0f0a",
            borderSubtle: "#1f2e1f",
            textStrong: "#c8facc",
            textMuted: "#6f9b72",
            accent: "#22c55e",
            onAccent: "#001b06",
            success: "#4ade80",
            secure: "#86efac",
            secureSurface: "#0c1f10",
            warning: "#ca8a04",
            warningSurface: "#262208",
            warningText: "#fde047"
        },
        {
            id: "nordfjord",
            name: "Nordfjord",
            tagline: "Calm arctic grays with frost-blue light",
            dark: true,
            rail: "#232831",
            railElevated: "#3b4252",
            railText: "#eceff4",
            sidebar: "#2e3440",
            sidebarInput: "#3b4252",
            sidebarActive: "#434c5e",
            sidebarText: "#aeb8cc",
            sidebarTextStrong: "#eceff4",
            sidebarTextSoft: "#d8dee9",
            sidebarTextMuted: "#7b869c",
            surfaceBase: "#2e3440",
            surfaceRaised: "#3b4252",
            borderSubtle: "#4c566a",
            textStrong: "#eceff4",
            textMuted: "#9aa5b8",
            accent: "#88c0d0",
            onAccent: "#17262b",
            success: "#a3be8c",
            secure: "#8aa8c5",
            secureSurface: "#2f3b51",
            warning: "#d08770",
            warningSurface: "#3a2d28",
            warningText: "#ebcb8b"
        },
        {
            id: "void-amoled",
            name: "Void AMOLED",
            tagline: "True-black minimalism with a violet pulse",
            dark: true,
            rail: "#000000",
            railElevated: "#17171c",
            railText: "#f5f5fa",
            sidebar: "#000000",
            sidebarInput: "#121216",
            sidebarActive: "#1c1c24",
            sidebarText: "#9d9dad",
            sidebarTextStrong: "#f5f5fa",
            sidebarTextSoft: "#c9c9d6",
            sidebarTextMuted: "#5c5c68",
            surfaceBase: "#000000",
            surfaceRaised: "#101014",
            borderSubtle: "#282836",
            textStrong: "#ededf2",
            textMuted: "#83839a",
            accent: "#a78bfa",
            onAccent: "#1c0f3a",
            success: "#34d399",
            secure: "#60a5fa",
            secureSurface: "#101c33",
            warning: "#d97706",
            warningSurface: "#241a05",
            warningText: "#fbbf24"
        },
        {
            id: "draculae",
            name: "Draculae",
            tagline: "Familiar midnight purples for the nocturnal",
            dark: true,
            rail: "#1d1e28",
            railElevated: "#343646",
            railText: "#f8f8f2",
            sidebar: "#21222c",
            sidebarInput: "#2b2d3a",
            sidebarActive: "#44475a",
            sidebarText: "#b6bdd9",
            sidebarTextStrong: "#f8f8f2",
            sidebarTextSoft: "#d5daef",
            sidebarTextMuted: "#6272a4",
            surfaceBase: "#282a36",
            surfaceRaised: "#313342",
            borderSubtle: "#44475a",
            textStrong: "#f8f8f2",
            textMuted: "#8a93b8",
            accent: "#bd93f9",
            onAccent: "#241242",
            success: "#50fa7b",
            secure: "#8be9fd",
            secureSurface: "#1c3a44",
            warning: "#b45309",
            warningSurface: "#3a2a17",
            warningText: "#ffb86c"
        },
        {
            id: "tokyo-midnight",
            name: "Tokyo Midnight",
            tagline: "Neon city indigo after the last train",
            dark: true,
            rail: "#121320",
            railElevated: "#24263b",
            railText: "#e6ebff",
            sidebar: "#16161e",
            sidebarInput: "#1f2133",
            sidebarActive: "#292e44",
            sidebarText: "#9aa5ce",
            sidebarTextStrong: "#e6ebff",
            sidebarTextSoft: "#c0caf5",
            sidebarTextMuted: "#58628d",
            surfaceBase: "#1a1b26",
            surfaceRaised: "#20222f",
            borderSubtle: "#31364d",
            textStrong: "#c0caf5",
            textMuted: "#7982a9",
            accent: "#7aa2f7",
            onAccent: "#0e1a36",
            success: "#9ece6a",
            secure: "#7dcfff",
            secureSurface: "#1b2b3d",
            warning: "#c2701d",
            warningSurface: "#38241a",
            warningText: "#ff9e64"
        },
        {
            id: "rosewood-dusk",
            name: "Rosewood Dusk",
            tagline: "Smoky mauve evenings with rose-lamp glow",
            dark: true,
            rail: "#170e12",
            railElevated: "#2f1c25",
            railText: "#ffeef4",
            sidebar: "#201319",
            sidebarInput: "#2c1a22",
            sidebarActive: "#3c2430",
            sidebarText: "#d3b2bf",
            sidebarTextStrong: "#ffeef4",
            sidebarTextSoft: "#ebcdd8",
            sidebarTextMuted: "#90687a",
            surfaceBase: "#1d1116",
            surfaceRaised: "#291921",
            borderSubtle: "#462a36",
            textStrong: "#f8e6ec",
            textMuted: "#b58a99",
            accent: "#fb7185",
            onAccent: "#37040e",
            success: "#34d399",
            secure: "#c084fc",
            secureSurface: "#2b1840",
            warning: "#d97706",
            warningSurface: "#322208",
            warningText: "#fcd34d"
        },
        {
            id: "solar-abyss",
            name: "Solar Abyss",
            tagline: "Deep-sea teal with warm solarized daylight",
            dark: true,
            rail: "#001f27",
            railElevated: "#0a4552",
            railText: "#eee8d5",
            sidebar: "#002b36",
            sidebarInput: "#073642",
            sidebarActive: "#0e4956",
            sidebarText: "#8fa9ad",
            sidebarTextStrong: "#eee8d5",
            sidebarTextSoft: "#b7c6c7",
            sidebarTextMuted: "#5d747b",
            surfaceBase: "#002b36",
            surfaceRaised: "#073642",
            borderSubtle: "#12505e",
            textStrong: "#dcd6c6",
            textMuted: "#8fa2a6",
            accent: "#2aa198",
            onAccent: "#00201d",
            success: "#859900",
            secure: "#469fde",
            secureSurface: "#06344c",
            warning: "#cb4b16",
            warningSurface: "#2f1608",
            warningText: "#e8956d"
        },
        {
            id: "velvet-grape",
            name: "Velvet Grape",
            tagline: "Aubergine velvet trimmed in antique gold",
            dark: true,
            rail: "#150d1c",
            railElevated: "#2a1b38",
            railText: "#f8f0ff",
            sidebar: "#1c1226",
            sidebarInput: "#271a34",
            sidebarActive: "#352345",
            sidebarText: "#c2abd6",
            sidebarTextStrong: "#f8f0ff",
            sidebarTextSoft: "#ddc9ec",
            sidebarTextMuted: "#7f689a",
            surfaceBase: "#191021",
            surfaceRaised: "#241730",
            borderSubtle: "#3e294e",
            textStrong: "#f1e6fb",
            textMuted: "#a48cbd",
            accent: "#e3b341",
            onAccent: "#2b1e02",
            success: "#4ade80",
            secure: "#a78bfa",
            secureSurface: "#241744",
            warning: "#ea580c",
            warningSurface: "#341d08",
            warningText: "#fdba74"
        },
        {
            id: "graphite-mono",
            name: "Graphite Mono",
            tagline: "Disciplined grayscale, one decisive blue",
            dark: true,
            rail: "#101113",
            railElevated: "#26282c",
            railText: "#f4f5f6",
            sidebar: "#171a1d",
            sidebarInput: "#212429",
            sidebarActive: "#2c3036",
            sidebarText: "#a9adb4",
            sidebarTextStrong: "#f4f5f6",
            sidebarTextSoft: "#ced2d8",
            sidebarTextMuted: "#686d75",
            surfaceBase: "#141619",
            surfaceRaised: "#1d2024",
            borderSubtle: "#2e3238",
            textStrong: "#eceef0",
            textMuted: "#8b9098",
            accent: "#4c8dff",
            onAccent: "#04162e",
            success: "#34d399",
            secure: "#93c5fd",
            secureSurface: "#16273e",
            warning: "#d97706",
            warningSurface: "#2b1c06",
            warningText: "#fbbf24"
        },
        {
            id: "gruvbox-hearth",
            name: "Gruvbox Hearth",
            tagline: "Warm retro browns beside a crackling fire",
            dark: true,
            rail: "#1b1d1e",
            railElevated: "#3a3735",
            railText: "#fbf1c7",
            sidebar: "#212223",
            sidebarInput: "#2e2c2a",
            sidebarActive: "#3c3836",
            sidebarText: "#bdae93",
            sidebarTextStrong: "#fbf1c7",
            sidebarTextSoft: "#d5c4a1",
            sidebarTextMuted: "#7c6f64",
            surfaceBase: "#282828",
            surfaceRaised: "#32302f",
            borderSubtle: "#453f3b",
            textStrong: "#ebdbb2",
            textMuted: "#a89984",
            accent: "#fe8019",
            onAccent: "#2c1200",
            success: "#b8bb26",
            secure: "#83a598",
            secureSurface: "#2c3634",
            warning: "#d79921",
            warningSurface: "#322808",
            warningText: "#fabd2f"
        },
        {
            id: "oceanic-material",
            name: "Oceanic Material",
            tagline: "Material ocean depths with soft seafoam",
            dark: true,
            rail: "#090b12",
            railElevated: "#191c2a",
            railText: "#eef1ff",
            sidebar: "#0f111a",
            sidebarInput: "#171923",
            sidebarActive: "#222533",
            sidebarText: "#9ba3c2",
            sidebarTextStrong: "#eef1ff",
            sidebarTextSoft: "#c3c9e0",
            sidebarTextMuted: "#5b6079",
            surfaceBase: "#101321",
            surfaceRaised: "#181b2c",
            borderSubtle: "#2c3147",
            textStrong: "#d6dcf5",
            textMuted: "#8289ab",
            accent: "#80cbc4",
            onAccent: "#0a2422",
            success: "#c3e88d",
            secure: "#82aaff",
            secureSurface: "#1a2440",
            warning: "#c26a45",
            warningSurface: "#33201a",
            warningText: "#ffb59d"
        },
        {
            id: "ink-contrast",
            name: "Ink & Signal",
            tagline: "Maximum contrast for maximum legibility",
            dark: true,
            rail: "#000000",
            railElevated: "#1f1f1f",
            railText: "#ffffff",
            sidebar: "#0a0a0a",
            sidebarInput: "#161616",
            sidebarActive: "#262626",
            sidebarText: "#d4d4d4",
            sidebarTextStrong: "#ffffff",
            sidebarTextSoft: "#e5e5e5",
            sidebarTextMuted: "#9c9c9c",
            surfaceBase: "#000000",
            surfaceRaised: "#121212",
            borderSubtle: "#3f3f3f",
            textStrong: "#ffffff",
            textMuted: "#b3b3b3",
            accent: "#00e5ff",
            onAccent: "#001418",
            success: "#00e676",
            secure: "#82b1ff",
            secureSurface: "#0d1f3c",
            warning: "#cc8400",
            warningSurface: "#2b1d00",
            warningText: "#ffd54f"
        },
        {
            id: "paper-atelier",
            name: "Paper Atelier",
            tagline: "Gallery-white calm with indigo ink",
            dark: false,
            rail: "#e9ebf1",
            railElevated: "#ffffff",
            railText: "#171c2a",
            sidebar: "#f2f4f8",
            sidebarInput: "#ffffff",
            sidebarActive: "#e2e6f0",
            sidebarText: "#4b5265",
            sidebarTextStrong: "#171c2a",
            sidebarTextSoft: "#333a4d",
            sidebarTextMuted: "#848ca1",
            surfaceBase: "#fbfcfe",
            surfaceRaised: "#ffffff",
            borderSubtle: "#cfd5e4",
            textStrong: "#171c2a",
            textMuted: "#6b7386",
            accent: "#4f46e5",
            onAccent: "#ffffff",
            success: "#0f9960",
            secure: "#1d4ed8",
            secureSurface: "#e6edff",
            warning: "#b45309",
            warningSurface: "#fff3e0",
            warningText: "#7c3d00"
        },
        {
            id: "arctic-daylight",
            name: "Arctic Daylight",
            tagline: "Bright fjord mornings in cool nordic light",
            dark: false,
            rail: "#d8dee9",
            railElevated: "#eceff4",
            railText: "#242933",
            sidebar: "#e5e9f0",
            sidebarInput: "#f4f6fa",
            sidebarActive: "#cdd6e5",
            sidebarText: "#4c566a",
            sidebarTextStrong: "#242933",
            sidebarTextSoft: "#3b4252",
            sidebarTextMuted: "#79859c",
            surfaceBase: "#eceff4",
            surfaceRaised: "#f8fafc",
            borderSubtle: "#bfcadd",
            textStrong: "#2e3440",
            textMuted: "#636c7e",
            accent: "#5578a4",
            onAccent: "#ffffff",
            success: "#47723f",
            secure: "#3f6796",
            secureSurface: "#dfe9f6",
            warning: "#b35c33",
            warningSurface: "#f8e8de",
            warningText: "#83421f"
        },
        {
            id: "sakura-morning",
            name: "Sakura Morning",
            tagline: "Soft petal pinks under spring light",
            dark: false,
            rail: "#f6e2e8",
            railElevated: "#fdf1f4",
            railText: "#2f1a21",
            sidebar: "#fae9ee",
            sidebarInput: "#fef7f9",
            sidebarActive: "#f3d3dd",
            sidebarText: "#6e4a55",
            sidebarTextStrong: "#2f1a21",
            sidebarTextSoft: "#503038",
            sidebarTextMuted: "#a27e88",
            surfaceBase: "#fdf7f8",
            surfaceRaised: "#ffffff",
            borderSubtle: "#e9cad3",
            textStrong: "#33202a",
            textMuted: "#886a75",
            accent: "#dc2d6c",
            onAccent: "#ffffff",
            success: "#178a5c",
            secure: "#7c3aed",
            secureSurface: "#f1e8fd",
            warning: "#b45309",
            warningSurface: "#fdf0dd",
            warningText: "#7a3e04"
        },
        {
            id: "mint-porcelain",
            name: "Mint Porcelain",
            tagline: "Cool mint glaze over quiet porcelain",
            dark: false,
            rail: "#dcebe4",
            railElevated: "#f0f8f4",
            railText: "#12241b",
            sidebar: "#e7f2ec",
            sidebarInput: "#f7fbf9",
            sidebarActive: "#d0e5da",
            sidebarText: "#3f5c4e",
            sidebarTextStrong: "#12241b",
            sidebarTextSoft: "#2c4437",
            sidebarTextMuted: "#729081",
            surfaceBase: "#f4faf7",
            surfaceRaised: "#ffffff",
            borderSubtle: "#bfd8ca",
            textStrong: "#16281f",
            textMuted: "#5e786a",
            accent: "#0c8479",
            onAccent: "#ffffff",
            success: "#15803d",
            secure: "#0369a1",
            secureSurface: "#e0f2fe",
            warning: "#a16207",
            warningSurface: "#fef6dd",
            warningText: "#713f12"
        },
        {
            id: "honey-parchment",
            name: "Honey Parchment",
            tagline: "Sunlit parchment with amber warmth",
            dark: false,
            rail: "#e8dcbf",
            railElevated: "#f7f0da",
            railText: "#2c2413",
            sidebar: "#f0e8cf",
            sidebarInput: "#faf4e2",
            sidebarActive: "#e3d5b3",
            sidebarText: "#6b5d3f",
            sidebarTextStrong: "#2c2413",
            sidebarTextSoft: "#4d4128",
            sidebarTextMuted: "#93835e",
            surfaceBase: "#fdf6e3",
            surfaceRaised: "#fffcf2",
            borderSubtle: "#ddcfa9",
            textStrong: "#382f1b",
            textMuted: "#7b7051",
            accent: "#a16b1b",
            onAccent: "#ffffff",
            success: "#4d7c0f",
            secure: "#0e7490",
            secureSurface: "#e0f4f8",
            warning: "#c2410c",
            warningSurface: "#fbe9dd",
            warningText: "#7c2d12"
        }
    ]

    function themeById(themeId) {
        for (var i = 0; i < catalog.length; ++i) {
            if (catalog[i].id === themeId) {
                return catalog[i]
            }
        }
        return catalog[0]
    }

    function linearColorChannel(value) {
        return value <= 0.03928
            ? value / 12.92
            : Math.pow((value + 0.055) / 1.055, 2.4)
    }

    function relativeLuminance(color) {
        return 0.2126 * linearColorChannel(color.r)
            + 0.7152 * linearColorChannel(color.g)
            + 0.0722 * linearColorChannel(color.b)
    }

    function contrastRatio(foreground, background) {
        var foregroundLuminance = relativeLuminance(foreground)
        var backgroundLuminance = relativeLuminance(background)
        var lighter = Math.max(foregroundLuminance, backgroundLuminance)
        var darker = Math.min(foregroundLuminance, backgroundLuminance)
        return (lighter + 0.05) / (darker + 0.05)
    }

    function readableTextColor(background) {
        var black = Qt.rgba(0, 0, 0, 1)
        var white = Qt.rgba(1, 1, 1, 1)
        return contrastRatio(black, background) >= contrastRatio(white, background)
            ? black
            : white
    }

    // Deterministic per-author identity color: FNV-1a over the device ID
    // picks a hue; text is selected dynamically for contrast.
    function authorColor(deviceId, dark) {
        var id = String(deviceId || "")
        if (id.length === 0) {
            return themeById("").accent
        }
        var hash = 0x811c9dc5
        for (var i = 0; i < id.length; ++i) {
            hash = hash ^ id.charCodeAt(i)
            hash = (hash * 0x01000193) >>> 0
        }
        var hue = (hash % 360) / 360.0
        return dark
            ? Qt.hsla(hue, 0.55, 0.62, 1.0)
            : Qt.hsla(hue, 0.62, 0.42, 1.0)
    }
}
